name: Build Firefox on Windows

on:
  workflow_dispatch:
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]

jobs:
  build-firefox:
    runs-on: windows-2022
    timeout-minutes: 180
    env:
      MOZILLA_SOURCE_DIR: C:\mozilla-source
      CARGO_TERM_COLOR: always
    steps:
      - name: 检出 workflow 仓库
        uses: actions/checkout@v4

      - name: 扩容
        shell: pwsh
        continue-on-error: true
        run: |
          .\clean.ps1

      - name: 安装 Chocolatey（包管理器）
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: 安装 wget
        run: |
          choco install -y wget
          refreshenv

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.11

      - name: 验证依赖
        run: |
          git --version
          python --version
          pip --version
          wget --version

      - name: 下载并安装 MozillaBuild
        run: |
          $url = "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe"
          $output = "$env:TEMP\MozillaBuildSetup.exe"
          Invoke-WebRequest $url -OutFile $output
          Start-Process -Wait -NoNewWindow -FilePath $output -ArgumentList '/S'

      - name: 创建源码目录
        run: |
          New-Item -ItemType Directory -Force -Path "C:\mozilla-source"

      - name: 下载 Firefox bootstrap.py
        working-directory: C:\mozilla-source
        run: |
          wget https://raw.githubusercontent.com/mozilla-firefox/firefox/refs/heads/main/python/mozboot/bin/bootstrap.py -OutFile bootstrap.py

      - name: 运行 bootstrap.py 引导源码和依赖
        working-directory: C:\mozilla-source
        run: |
          python bootstrap.py --no-interactive --application-choice=browser

      - name: 检出 Firefox 源码（central 分支）
        working-directory: C:\mozilla-source
        run: |
          if (-Not (Test-Path "C:\mozilla-source\firefox")) {
            git clone https://github.com/mozilla/gecko-dev.git firefox
          }
          cd firefox
          git fetch origin
          git checkout central

      - name: 构建 Firefox
        working-directory: C:\mozilla-source\firefox
        run: |
          C:\mozilla-build\start-shell.bat -c "./mach build"

      - name: 输出构建产物目录
        working-directory: C:\mozilla-source\firefox
        run: |
          dir obj-*\dist\bin

      # 可选: 上传构建产物
      - name: 上传 Firefox 可执行文件
        uses: actions/upload-artifact@v4
        with:
          name: firefox-build
          path: |
            C:\mozilla-source\firefox\obj-*\dist\bin\firefox.exe
            C:\mozilla-source\firefox\obj-*\dist\bin\*.dll
